# Development tasks

[tasks.audit]
command = "cargo"
args = ["audit", "${@}"]

[tasks.watch]
command = "cargo"
args = ["watch", "-x", "${@}"]

# Publish task

[tasks.release]
command = "cargo"
args = ["release", "${@}"]
