name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.42.0
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        if: ${{ matrix.rust != 'stable' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy
          override: true
      - name: Install Rust toolchain + clippy
        if: ${{ matrix.rust == 'stable' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: api
      - name: Build
        if: ${{ matrix.rust != 'stable' }}
        run: cargo check --verbose --all-targets
      - name: Build and lint
        if: ${{ matrix.rust == 'stable' }}
        run: cargo clippy --verbose --all-targets
  format:
    name: Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: rustfmt
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: api
      - name: Check format
        run: cargo fmt -- --check --verbose
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.42.0
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: api
      - name: Run tests
        if: ${{ !(matrix.rust == 'stable' && github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        run: cargo test
      - name: Run tests and generate coverage report
        if: ${{ matrix.rust == 'stable' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: cargo tarpaulin -v --all-features --ignore-tests --out Xml
      - name: Upload coverage report
        if: ${{ matrix.rust == 'stable' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
